module.exports = [
  {
    name: "什么是田野考古",
    summary: "田野考古是考古学研究得以展开的核心",
    father: "",
    category: "C1",
    learningTime: 10,
    coverImage: "test.jpg",
    order: 1,
  },
  {
    name: "田野考古的前期准备",
    summary: "凡是预则立，不预则废",
    father: "",
    category: "C1",
    learningTime: 10,
    coverImage: "test.jpg",
    order: 2,
  },
  {
    name: "田野考古的野外工作",
    summary: "想要获得尽可能多的历史信息，就要科学地开展野外田野考古工作",
    father: "",
    category: "C1",
    learningTime: 10,
    coverImage: "test.jpg",
    order: 3,
  },
  {
    name: "田野考古的室内工作",
    summary: "室外发掘的完成不代表整个田野考古工作的完成",
    father: "",
    category: "C1",
    learningTime: 10,
    coverImage: "test.jpg",
    order: 4,
  },
  {
    name: "编写田野考古报告",
    summary: "是终点，也是起点",
    father: "",
    category: "C1",
    learningTime: 10,
    coverImage: "test.jpg",
    order: 5,
  },
  {
    name: "考古工地的管理",
    summary: "管人、管物、管流程",
    father: "",
    category: "C1",
    learningTime: 10,
    coverImage: "test.jpg",
    order: 6,
  },
  {
    name: "什么是考古学",
    summary: "揭开考古学的神秘面纱",
    father: "什么是田野考古",
    category: "C1",
    learningTime: 10,
    coverImage: "test.jpg",
    order: 1,
  },
  {
    name: "为什么要进行田野考古",
    summary: "为了获取实物资料、开展研究",
    father: "什么是田野考古",
    category: "C1",
    learningTime: 10,
    coverImage: "test.jpg",
    order: 2,
  },
  {
    name: "怎样进行田野考古工作",
    summary: "做好前期准备-野外工作-室内整理-编写、发表报告四个阶段的工作",
    father: "什么是田野考古",
    category: "C1",
    learningTime: 10,
    coverImage: "test.jpg",
    order: 3,
  },
  {
    name: "为什么盗掘令人憎恶",
    summary: "我们因此丧失了通往过去、通往自身的途径",
    father: "什么是田野考古",
    category: "C1",
    learningTime: 10,
    coverImage: "test.jpg",
    order: 4,
  },
  {
    name: "田野考古的理论依据",
    summary: "理论是抽象的，实践是复杂的",
    father: "田野考古的野外工作",
    category: "C1",
    learningTime: 10,
    coverImage: "test.jpg",
    order: 1,
  },
  {
    name: "考古调查",
    summary: "在基本不破坏遗址或遗迹的情况下，发现和获取遗存资料",
    father: "田野考古的野外工作",
    category: "C1",
    learningTime: 10,
    coverImage: "test.jpg",
    order: 2,
  },
  {
    name: "考古发掘",
    summary: "2.5维的考古发掘",
    father: "田野考古的野外工作",
    category: "C1",
    learningTime: 10,
    coverImage: "test.jpg",
    order: 3,
  },
  {
    name: "考古发掘的方法",
    summary: "在我国，最常见的发掘方法是探方法",
    father: "考古发掘",
    category: "C1",
    learningTime: 10,
    coverImage: "test.jpg",
    order: 1,
  },
  {
    name: "发掘资料采集",
    summary: "系统性、针对性、有效性",
    father: "考古发掘",
    category: "C1",
    learningTime: 10,
    coverImage: "test.jpg",
    order: 2,
  },
  {
    name: "考古发掘记录",
    summary: "尽量全面、完善地记录在发掘过程中所获的一切信息",
    father: "考古发掘",
    category: "C1",
    learningTime: 10,
    coverImage: "test.jpg",
    order: 3,
  },
  {
    name: "遗址、遗物、遗迹的保护",
    summary: "原始信息的保存",
    father: "考古发掘",
    category: "C1",
    learningTime: 10,
    coverImage: "test.jpg",
    order: 4,
  },
  {
    name: "考古报告的要求与内容",
    summary: "高质量的野外工作和室内整理工作，是编写考古报告的基础",
    father: "编写田野考古报告",
    category: "C1",
    learningTime: 10,
    coverImage: "test.jpg",
    order: 3,
  },
  {
    name: "编写田野考古报告的注意事项",
    summary: "尽快编写和发表田野考古报告",
    father: "编写田野考古报告",
    category: "C1",
    learningTime: 10,
    coverImage: "test.jpg",
    order: 2,
  },
  {
    name: "什么是田野考古报告",
    summary: "田野考古工作成果报告书",
    father: "编写田野考古报告",
    category: "C1",
    learningTime: 10,
    coverImage: "test.jpg",
    order: 1,
  },
  {
    name: "发掘资料管理",
    summary: "考古发掘所获实物及相关记录极其重要",
    father: "考古工地的管理",
    category: "C1",
    learningTime: 10,
    coverImage: "test.jpg",
    order: 3,
  },
  {
    name: "考古发掘单位和领队职责",
    summary: "领队负责制",
    father: "考古工地的管理",
    category: "C1",
    learningTime: 10,
    coverImage: "test.jpg",
    order: 2,
  },
  {
    name: "考古工作者的素养",
    summary: "明确考古资料所有权",
    father: "考古工地的管理",
    category: "C1",
    learningTime: 10,
    coverImage: "test.jpg",
    order: 1,
  },
  {
    name: "考古勘探工具",
    summary: "等待高勇来编写这段摘要",
    father: "",
    category: "C2",
    learningTime: 10,
    coverImage: "tools.jpg",
    order: 1,
  },
  {
    name: "考古发掘工具",
    summary: "等待高勇来编写这段摘要",
    father: "",
    category: "C2",
    learningTime: 10,
    coverImage: "tools.jpg",
    order: 2,
  },
  {
    name: "考古测量工具",
    summary: "等待高勇来编写这段摘要",
    father: "",
    category: "C2",
    learningTime: 10,
    coverImage: "tools.jpg",
    order: 3,
  },
  {
    name: "圆明园遗址公园概述",
    summary: "等待高勇来编写这段摘要",
    father: "",
    category: "C3",
    learningTime: 10,
    coverImage: "ymy.jpg",
    order: 1,
  },
  {
    name: "圆明园考古工作回顾",
    summary: "等待高勇来编写这段摘要",
    father: "",
    category: "C3",
    learningTime: 10,
    coverImage: "ymy.jpg",
    order: 2,
  },
  {
    name: "圆明园发掘遗址举例",
    summary: "等待高勇来编写这段摘要",
    father: "",
    category: "C3",
    learningTime: 16,
    coverImage: "ymy.jpg",
    order: 3,
  },
  {
    name: "圆明园管理处有组织的清理工作",
    summary: "等待高勇来编写这段摘要",
    father: "圆明园考古工作回顾",
    category: "C3",
    learningTime: 10,
    coverImage: "ymy.jpg",
    order: 1,
  },
  {
    name: "圆明园最早的正式考古勘探发掘工作",
    summary: "等待高勇来编写这段摘要",
    father: "圆明园考古工作回顾",
    category: "C3",
    learningTime: 10,
    coverImage: "ymy.jpg",
    order: 2,
  },
  {
    name: "21世纪以来的圆明园考古工作",
    summary: "等待高勇来编写这段摘要",
    father: "圆明园考古工作回顾",
    category: "C3",
    learningTime: 15,
    coverImage: "ymy.jpg",
    order: 3,
  },
  {
    name: "圆明园大宫门遗址",
    summary: "等待高勇来编写这段摘要",
    father: "圆明园发掘遗址举例",
    category: "C3",
    learningTime: 17,
    coverImage: "ymy.jpg",
    order: 1,
  },
  {
    name: "长春园含经堂遗址",
    summary: "等待高勇来编写这段摘要",
    father: "圆明园发掘遗址举例",
    category: "C3",
    learningTime: 18,
    coverImage: "ymy.jpg",
    order: 2,
  },
  {
    name: "海晏堂蓄水楼遗址",
    summary: "等待高勇来编写这段摘要",
    father: "圆明园发掘遗址举例",
    category: "C3",
    learningTime: 19,
    coverImage: "ymy.jpg",
    order: 3,
  },
];
