module.exports = [
  {
    name: "什么是田野考古",
    summary: "测试摘要仅用于前端填充数据使用 测试摘要仅用于前端填充数据使用1",
    father: "",
    category: "C1",
    learningTime: 10,
    coverImage: "test.jpg",
    order: 1,
  },
  {
    name: "田野考古的前期准备",
    summary: "测试摘要仅用于前端填充数据使用 测试摘要仅用于前端填充数据使用2",
    father: "",
    category: "C1",
    learningTime: 10,
    coverImage: "test.jpg",
    order: 2,
  },
  {
    name: "田野考古的野外工作",
    summary: "测试摘要仅用于前端填充数据使用 测试摘要仅用于前端填充数据使用3",
    father: "",
    category: "C1",
    learningTime: 10,
    coverImage: "test.jpg",
    order: 3,
  },
  {
    name: "田野考古的室内工作",
    summary: "测试摘要仅用于前端填充数据使用 测试摘要仅用于前端填充数据使用4",
    father: "",
    category: "C1",
    learningTime: 10,
    coverImage: "test.jpg",
    order: 4,
  },
  {
    name: "编写考古报告",
    summary: "测试摘要仅用于前端填充数据使用 测试摘要仅用于前端填充数据使用5",
    father: "",
    category: "C1",
    learningTime: 10,
    coverImage: "test.jpg",
    order: 5,
  },
  {
    name: "考古工地的管理",
    summary: "测试摘要仅用于前端填充数据使用 测试摘要仅用于前端填充数据使用6",
    father: "",
    category: "C1",
    learningTime: 10,
    coverImage: "test.jpg",
    order: 6,
  },
  {
    name: "什么是考古学",
    summary: "揭开考古学的神秘面纱",
    father: "什么是田野考古",
    category: "C1",
    learningTime: 10,
    coverImage: "test.jpg",
    order: 1,
  },
  {
    name: "为什么要进行田野考古",
    summary: "测试摘要仅用于前端填充数据使用 测试摘要仅用于前端填充数据使用8",
    father: "什么是田野考古",
    category: "C1",
    learningTime: 10,
    coverImage: "test.jpg",
    order: 2,
  },
  {
    name: "怎么进行田野考古工作",
    summary: "测试摘要仅用于前端填充数据使用 测试摘要仅用于前端填充数据使用9",
    father: "什么是田野考古",
    category: "C1",
    learningTime: 10,
    coverImage: "test.jpg",
    order: 3,
  },
  {
    name: "为什么盗掘令人憎恶",
    summary: "测试摘要仅用于前端填充数据使用 测试摘要仅用于前端填充数据使用10",
    father: "什么是田野考古",
    category: "C1",
    learningTime: 10,
    coverImage: "test.jpg",
    order: 4,
  },
  {
    name: "考古调查",
    summary: "测试摘要仅用于前端填充数据使用 测试摘要仅用于前端填充数据使用11",
    father: "田野考古的野外工作",
    category: "C1",
    learningTime: 10,
    coverImage: "test.jpg",
    order: 1,
  },
  {
    name: "考古发掘",
    summary: "测试摘要仅用于前端填充数据使用 测试摘要仅用于前端填充数据使用12",
    father: "田野考古的野外工作",
    category: "C1",
    learningTime: 10,
    coverImage: "test.jpg",
    order: 2,
  },
  {
    name: "考古发掘的理论依据",
    summary: "测试摘要仅用于前端填充数据使用 测试摘要仅用于前端填充数据使用13",
    father: "考古发掘",
    category: "C1",
    learningTime: 10,
    coverImage: "test.jpg",
    order: 1,
  },
  {
    name: "考古发掘的方法",
    summary: "测试摘要仅用于前端填充数据使用 测试摘要仅用于前端填充数据使用14",
    father: "考古发掘",
    category: "C1",
    learningTime: 10,
    coverImage: "test.jpg",
    order: 2,
  },
  {
    name: "发掘资料采集",
    summary: "测试摘要仅用于前端填充数据使用 测试摘要仅用于前端填充数据使用15",
    father: "考古发掘",
    category: "C1",
    learningTime: 10,
    coverImage: "test.jpg",
    order: 3,
  },
  {
    name: "考古发掘记录",
    summary: "测试摘要仅用于前端填充数据使用 测试摘要仅用于前端填充数据使用16",
    father: "考古发掘",
    category: "C1",
    learningTime: 10,
    coverImage: "test.jpg",
    order: 4,
  },
  {
    name: "遗址、遗物、遗迹的保护",
    summary: "测试摘要仅用于前端填充数据使用 测试摘要仅用于前端填充数据使用17",
    father: "考古发掘",
    category: "C1",
    learningTime: 10,
    coverImage: "test.jpg",
    order: 5,
  },
  {
    name: "资料整理",
    summary: "测试摘要仅用于前端填充数据使用 测试摘要仅用于前端填充数据使用18",
    father: "田野考古的室内工作",
    category: "C1",
    learningTime: 10,
    coverImage: "test.jpg",
    order: 1,
  },
  {
    name: "室内整理",
    summary: "测试摘要仅用于前端填充数据使用 测试摘要仅用于前端填充数据使用19",
    father: "资料整理",
    category: "C1",
    learningTime: 10,
    coverImage: "test.jpg",
    order: 1,
  },
  {
    name: "考古绘图",
    summary: "测试摘要仅用于前端填充数据使用 测试摘要仅用于前端填充数据使用20",
    father: "资料整理",
    category: "C1",
    learningTime: 10,
    coverImage: "test.jpg",
    order: 2,
  },
  {
    name: "考古摄影",
    summary: "测试摘要仅用于前端填充数据使用 测试摘要仅用于前端填充数据使用21",
    father: "资料整理",
    category: "C1",
    learningTime: 10,
    coverImage: "test.jpg",
    order: 3,
  },
  {
    name: "田野考古报告的要求",
    summary: "测试摘要仅用于前端填充数据使用 测试摘要仅用于前端填充数据使用22",
    father: "编写田野考古报告",
    category: "C1",
    learningTime: 10,
    coverImage: "test.jpg",
    order: 1,
  },
  {
    name: "田野考古报告的体例、设计、方法",
    summary: "测试摘要仅用于前端填充数据使用 测试摘要仅用于前端填充数据使用23",
    father: "编写田野考古报告",
    category: "C1",
    learningTime: 10,
    coverImage: "test.jpg",
    order: 2,
  },
  {
    name: "考古工地的工作人员管理",
    summary: "测试摘要仅用于前端填充数据使用 测试摘要仅用于前端填充数据使用24",
    father: "考古工地的管理",
    category: "C1",
    learningTime: 10,
    coverImage: "test.jpg",
    order: 1,
  },
  {
    name: "考古工作者的素养",
    summary: "测试摘要仅用于前端填充数据使用 测试摘要仅用于前端填充数据使用25",
    father: "考古工地的管理",
    category: "C1",
    learningTime: 10,
    coverImage: "test.jpg",
    order: 2,
  },
  {
    name: "摄录设备",
    summary: "测试摘要仅用于前端填充数据使用 测试摘要仅用于前端填充数据使用26",
    father: "",
    category: "C2",
    learningTime: 10,
    coverImage: "tools.jpg",
    order: 2,
  },
  {
    name: "记录用品",
    summary: "测试摘要仅用于前端填充数据使用 测试摘要仅用于前端填充数据使用27",
    father: "",
    category: "C2",
    learningTime: 10,
    coverImage: "tools.jpg",
    order: 3,
  },
  {
    name: "探查工具",
    summary: "测试摘要仅用于前端填充数据使用 测试摘要仅用于前端填充数据使用28",
    father: "",
    category: "C2",
    learningTime: 10,
    coverImage: "tools.jpg",
    order: 4,
  },
  {
    name: "发掘工具",
    summary: "测试摘要仅用于前端填充数据使用 测试摘要仅用于前端填充数据使用29",
    father: "",
    category: "C2",
    learningTime: 10,
    coverImage: "tools.jpg",
    order: 5,
  },
  {
    name: "其他工具",
    summary: "测试摘要仅用于前端填充数据使用 测试摘要仅用于前端填充数据使用30",
    father: "",
    category: "C2",
    learningTime: 10,
    coverImage: "tools.jpg",
    order: 6,
  },
  {
    name: "传统测绘工具",
    summary: "测试摘要仅用于前端填充数据使用 测试摘要仅用于前端填充数据使用31",
    father: "测绘工具",
    category: "C2",
    learningTime: 10,
    coverImage: "tools.jpg",
    order: 1,
  },
  {
    name: "全站仪",
    summary: "测试摘要仅用于前端填充数据使用 测试摘要仅用于前端填充数据使用32",
    father: "测绘工具",
    category: "C2",
    learningTime: 10,
    coverImage: "tools.jpg",
    order: 2,
  },
  {
    name: "rtk",
    summary: "测试摘要仅用于前端填充数据使用 测试摘要仅用于前端填充数据使用33",
    father: "测绘工具",
    category: "C2",
    learningTime: 10,
    coverImage: "tools.jpg",
    order: 3,
  },
  {
    name: "三维激光扫描仪",
    summary: "测试摘要仅用于前端填充数据使用 测试摘要仅用于前端填充数据使用34",
    father: "测绘工具",
    category: "C2",
    learningTime: 10,
    coverImage: "tools.jpg",
    order: 4,
  },
  {
    name: "洛阳铲",
    summary: "测试摘要仅用于前端填充数据使用 测试摘要仅用于前端填充数据使用35",
    father: "探查工具",
    category: "C2",
    learningTime: 10,
    coverImage: "tools.jpg",
    order: 1,
  },
  {
    name: "探地雷达",
    summary: "测试摘要仅用于前端填充数据使用 测试摘要仅用于前端填充数据使用36",
    father: "探查工具",
    category: "C2",
    learningTime: 10,
    coverImage: "tools.jpg",
    order: 2,
  },
  {
    name: "多光谱遥感相机",
    summary: "测试摘要仅用于前端填充数据使用 测试摘要仅用于前端填充数据使用37",
    father: "探查工具",
    category: "C2",
    learningTime: 10,
    coverImage: "tools.jpg",
    order: 3,
  },
  {
    name: "圆明园概述",
    summary: "测试摘要仅用于前端填充数据使用 测试摘要仅用于前端填充数据使用38",
    father: "",
    category: "C3",
    learningTime: 10,
    coverImage: "ymy.jpg",
    order: 1,
  },
  {
    name: "圆明园考古工作历程",
    summary: "测试摘要仅用于前端填充数据使用 测试摘要仅用于前端填充数据使用39",
    father: "",
    category: "C3",
    learningTime: 10,
    coverImage: "ymy.jpg",
    order: 2,
  },
  {
    name: "第一阶段",
    summary: "测试摘要仅用于前端填充数据使用 测试摘要仅用于前端填充数据使用40",
    father: "圆明园考古工作历程",
    category: "C3",
    learningTime: 10,
    coverImage: "ymy.jpg",
    order: 1,
  },
  {
    name: "第二阶段",
    summary: "测试摘要仅用于前端填充数据使用 测试摘要仅用于前端填充数据使用41",
    father: "圆明园考古工作历程",
    category: "C3",
    learningTime: 10,
    coverImage: "ymy.jpg",
    order: 2,
  },
  {
    name: "第三阶段",
    summary: "测试摘要仅用于前端填充数据使用 测试摘要仅用于前端填充数据使用42",
    father: "圆明园考古工作历程",
    category: "C3",
    learningTime: 15,
    coverImage: "ymy.jpg",
    order: 3,
  },
  {
    name: "圆明园重要遗址介绍",
    summary: "测试摘要仅用于前端填充数据使用 测试摘要仅用于前端填充数据使用43",
    father: "",
    category: "C3",
    learningTime: 16,
    coverImage: "ymy.jpg",
    order: 3,
  },
  {
    name: "圆明园藻园遗址",
    summary: "测试摘要仅用于前端填充数据使用 测试摘要仅用于前端填充数据使用44",
    father: "圆明园重要遗址介绍",
    category: "C3",
    learningTime: 17,
    coverImage: "ymy.jpg",
    order: 1,
  },
  {
    name: "长春园含经堂遗址",
    summary: "测试摘要仅用于前端填充数据使用 测试摘要仅用于前端填充数据使用45",
    father: "圆明园重要遗址介绍",
    category: "C3",
    learningTime: 18,
    coverImage: "ymy.jpg",
    order: 2,
  },
  {
    name: "长春园宫门遗址",
    summary: "测试摘要仅用于前端填充数据使用 测试摘要仅用于前端填充数据使用46",
    father: "圆明园重要遗址介绍",
    category: "C3",
    learningTime: 19,
    coverImage: "ymy.jpg",
    order: 3,
  },
];
